config/routes.rb
Rails.application.routes.draw do
  get 'charts/index'
  devise_for :users
  get '/lp', to: 'landing_pages#index'
  root to: 'receipts#index'
  resources :receipts, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_many :receipt_details, inverse_of: :receipt, dependent: :destroy
  accepts_nested_attributes_for :receipt_details
  validates :total_price, numericality: { greater_than: 0 }
  validates :receipt_details, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/receipt_detail.rb
class ReceiptDetail < ApplicationRecord
  belongs_to :receipt
  validates :name, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are: :recoverable, 
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @countries = Country.all
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def index
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @receipts = Receipt.paginate(page: params[:page], per_page: 10)
  end

  def new
    @receipt = Receipt.new
    @receipt.receipt_details.build
  end

  def create
    @receipt = Receipt.new(receipt_params)
    if @receipt.save
      redirect_to :receipts
    else
      render 'receipts/new'
    end
  end

  def edit
    @receipt = Receipt.find(params[:id])
  end

  def update
    @receipt = Receipt.find(params[:id])
    if @receipt.update(receipt_params)
      # 削除ボタンが押された明細を削除する
      receipt_params[:receipt_details_attributes].each do |detail|
        if detail[1][:_destroy] != "false"
          @receipt.receipt_details.find(detail[1][:id]).destroy
        end
      end
      redirect_to :receipts
    else
      render 'receipts/edit'
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy
    redirect_to :receipts
  end

  private
    def receipt_params
      params.require(:receipt).permit(:total_price, receipt_details_attributes: [:id, :name, :price, :quantity, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
  # for devise
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/charts/index.html.erb
<h1>Charts#index</h1>
<p>Find me in app/views/charts/index.html.erb</p>

<div class="container">
  <div class="row g-3">
    <p class="h2">Countries(group by continent)</p>
    <div class="col-md-6">
      <p class="h3 text-center">Count</p>
      <%= pie_chart @countries.group(:continent).count %>
    </div>
    <div class="col-md-6">
      <p class="h3 text-center">Population</p>
      <%= pie_chart @countries.group(:continent).sum(:Population) %>
    </div>
    <div class="col-md-6">
      <p class="h3 text-center">Surface</p>
      <%= pie_chart @countries.group(:continent).sum(:surface_area) %>
    </div>
    <div class="col-md-6">
      <p class="h3 text-center">GNP</p>
      <%= pie_chart @countries.group(:continent).sum(:gnp) %>
    </div>
    <div class="col-md-6">
      <p class="h3 text-center">Life Expectancy</p>
      <%= bar_chart @countries.group(:continent).average(:life_expectancy) %>
    </div>
  </div>
</div>

app/views/landing_pages/_contactus.html.erb
<section class="py-5 bg-light" id="contactUs">
  <div class="container">
    <div class="row text-center">
      <div class="col">
        <h1>お問い合わせ</h1>
      </div>
    </div>
    <div class="row pt-3">
      <!--left-->
      <div class="col-md-4">
        <div class="hstack mb-3">
          <i class="bi bi-envelope-fill text-danger fs-3"></i>
          <div class="ms-3">
            <h5 class="mb-1">メール</h5>
            <span class="text-muted">info@example.com</span>
          </div>
        </div>
        <div class="hstack mb-3">
          <i class="bi bi-telephone-fill text-danger fs-3"></i>
          <div class="ms-3">
            <h5 class="mb-1">電話番号</h5>
            <span class="text-muted">03-1234-5678</span>
          </div>
        </div>
      </div>
      <!--right-->
      <div class="col-md-8">
        <form action="#" class="post">
          <div class="mb-3">
            <input type="text" class="form-control shadow-sm" placeholder="氏名">
          </div>
          <div class="mb-3">
            <input type="text" class="form-control shadow-sm" placeholder="Eメール">
          </div>
          <div class="mb-3">
            <textarea class="form-control shadow-sm" rows="4" placeholder="内容"></textarea>
          </div>
          <div class="col-12">
            <button class="btn btn-danger rounded-pill px-5">
              送信
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

app/views/landing_pages/_content.html.erb
<section class="py-5" id="content">
  <div class="container py-3">
    <row class="text-center pb-3">
      <div class="col">
        <h2>講座内容（一例）</h2>
      </div>
    </row>
    <div class="row row-cols-1 row-cols-md-3 g-3">
      <!--プログラミング基礎-->
      <div class="col">
        <div class="card shadow h-100">
          <img src="https://source.unsplash.com/640x426/daily?computer" alt="Computer">
          <div class="card-body">
            <h5 class="card-title">プログラミング基礎</h5>
            <p class="card-text">プログラミングの基礎を、ゼロから学びます。</p>
          </div>
        </div>
      </div>
      <!--フレームワーク学習-->
      <div class="col">
        <div class="card shadow h-100">
          <img src="https://source.unsplash.com/640x426/daily?coding" alt="Coding">
          <div class="card-body">
            <h5 class="card-title">フレームワーク学習</h5>
            <p class="card-text">実務で必要となるフレームワークを学びます。</p>
          </div>
        </div>
      </div>
      <!--クラウドシステム構築-->
      <div class="col">
        <div class="card shadow h-100">
          <img src="https://source.unsplash.com/640x426/daily?network" alt="Network">
          <div class="card-body">
            <h5 class="card-title">クラウドシステム構築</h5>
            <p class="card-text">AWSやMicrosoft Azureの構築方法を学びます。</p>
          </div>
        </div>
      </div>
      <!--UI・UX-->
      <div class="col">
        <div class="card shadow h-100">
          <img src="https://source.unsplash.com/640x426/daily?design" alt="Design">
          <div class="card-body">
            <h5 class="card-title">UI・UX</h5>
            <p class="card-text">デザインの原則を学びます。</p>
          </div>
        </div>
      </div>
      <!--チームワーク-->
      <div class="col">
        <div class="card shadow h-100">
          <img src="https://source.unsplash.com/640x426/daily?team" alt="Team">
          <div class="card-body">
            <h5 class="card-title">チームワーク</h5>
            <p class="card-text">共同作業をすることで、チームワークを学びます。</p>
          </div>
        </div>
      </div>
      <!--学習方法-->
      <div class="col">
        <div class="card shadow h-100">
          <img src="https://source.unsplash.com/640x426/daily?study" alt="Study">
          <div class="card-body">
            <h5 class="card-title">学習方法</h5>
            <p class="card-text">効率の良い、ITの学習方法を学びます。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- 相談(リンク) -->
<section class="py-5 bg-danger text-white">
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <p>受講をお悩みですか？</p>
        <h2 class="mb-3">今なら、相談も受け付けております。</h2>
        <a href="#contactUs" class="btn btn-dark px-5 shadow">
          相談する
        </a>
      </div>
    </div>
  </div>
</section>

app/views/landing_pages/_course.html.erb
<section class="py-5" id="course">
  <div class="container text-center py-3">
    <div class="row pb-3">
      <div class="col">
        <h1>どのコースをお望みですか？</h1>
      </div>
    </div>
    <div class="row g-4">
      <!--programming-->
      <div class="col-md-4">
        <!--card-->
        <div class="border p-3 shadow">
          <i class="bi bi-laptop text-danger fs-1"></i>
          <h5>プログラミング</h5>
          <p class="text-muted">アプリを作成したい人に最適です。</p>
          <a href="#content" class="btn btn-danger rounded-pill">
            詳細はこちら
          </a>
        </div>
      </div>
      <!--network-->
      <div class="col-md-4">
        <!--card-->
        <div class="border p-3 shadow">
          <i class="bi bi-cloud text-danger fs-1"></i>
          <h5>ネットワーク</h5>
          <p class="text-muted">システムを管理したい人に適しています。</p>
          <a href="#content" class="btn btn-danger rounded-pill">
            詳細はこちら
          </a>
        </div>
      </div>
      <!--design-->
      <div class="col-md-4">
        <!--card-->
        <div class="border p-3 shadow">
          <i class="bi bi-brush text-danger fs-1"></i>
          <h5>デザイン</h5>
          <p class="text-muted">デザインを学びたい人に最適です。</p>
          <a href="#content" class="btn btn-danger rounded-pill">
            詳細はこちら
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/landing_pages/_footer.html.erb
<footer class="mt-auto py-2 bg-dark bg-gradient text-white">
  <div class="container text-center">
    ©2021 CyberMissions
  </div>
</footer>

app/views/landing_pages/_home.html.erb
<section class="bg-danger text-white" id="home" style="padding: 80px 0 50px">
  <div class="container py-3">
    <div class="row align-items-center g-4">
      <!-- left -->
      <div class="col-md-7">
        <h1>ITを学んで、自己投資しませんか？</h1>
        <p>今なら無料カウンセリング実施中</p>
        <a href="#contactUs" class="btn btn-dark px-5 shadow-lg">相談する</a>
      </div>
      <!-- right -->
      <div class="col-md-5 text-center">
        <%= image_tag 'undraw_content_team_3epn.svg', class: "img-fluid" %>
      </div>
    </div>
  </div>
</section>

app/views/landing_pages/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient fixed-top">
  <div class="container">
    <a href="#" class="navbar-brand">
      <i class="bi bi-app-indicator"></i>
      ITスクール
    </a>
    <!-- toggle button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- link -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a href="#home" class="nav-link active" aria-current="page">
            ホーム
          </a>
        </li>
        <li class="nav-item">
          <a href="#course" class="nav-link">コース</a>
        </li>
        <li class="nav-item">
          <a href="#reputation" class="nav-link">評判</a>
        </li>
        <li class="nav-item">
          <a href="#content" class="nav-link">講座内容</a>
        </li>
        <li class="nav-item">
          <a href="#pricing" class="nav-link">価格</a>
        </li>
        <li class="nav-item">
          <a href="#contactUs" class="nav-link">お問い合わせ</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/landing_pages/_pricing.html.erb
<section class="py-5" id="pricing">
  <div class="container text-center py-3">
    <div class="row pb-3">
      <div class="col">
        <h1>価格</h1>
      </div>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-3">

      <!-- 無料 -->
      <div class="col">
        <!-- カード -->
        <div class="card shadow-sm h-100">
          <div class="card-header">
            <h4 class="fw-normal">無料</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title text-danger">0円</h1>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">カウンセリング</li>
              <li class="list-group-item">チャットサポート</li>
            </ul>
          </div>
          <div class="card-footer">
            <a href="#" class="w-100 btn btn-outline-danger">
              無料登録
            </a>
          </div>
        </div>
      </div>

      <!-- スタンダード -->
      <div class="col">
        <div class="card shadow-sm h-100">
          <div class="card-header">
            <h4 class="fw-normal">スタンダード</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title text-danger">2,980円</h1>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">カウンセリング</li>
              <li class="list-group-item">チャットサポート</li>
              <li class="list-group-item">全ての講座が受け放題</li>
            </ul>
          </div>
          <div class="card-footer">
            <a href="#" class="w-100 btn btn-danger">
              会員登録
            </a>
          </div>
        </div>
      </div>

      <!-- プレミアム -->
      <div class="col">
        <div class="card shadow-sm border-danger h-100">
          <div class="card-header text-white bg-danger">
            <h4 class="fw-normal">プレミアム</h4>
          </div>
          <div class="card-body pb-0">
            <h1 class="card-title text-danger">9,800円</h1>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">カウンセリング</li>
              <li class="list-group-item">チャットサポート</li>
              <li class="list-group-item">全ての講座が受け放題</li>
              <li class="list-group-item">オンライン個別指導</li>
            </ul>
          </div>
          <div class="card-footer">
            <a href="#" class="w-100 btn btn-danger">
              会員登録
            </a>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/landing_pages/_reputation.html.erb
<section class="py-5 bg-light" id="reputation">
  <div class="container text-center py-3">
    <div class="row pb-3">
      <div class="col">
        <h1>受講生の皆様から、支持されています</h1>
      </div>
    </div>
    <div class="row row-cols-1 row-cols-md-4">
      <!--年間受講者-->
      <div class="col">
        <div class="card text-white bg-primary mb-3 shadow">
          <div class="card-body">
            <h1 class="card-title">600人</h1>
            <p class="card-text">年間受講者</p>
          </div>
        </div>
      </div>

      <!--リピート率-->
      <div class="col">
        <div class="card text-white bg-success mb-3 shadow">
          <div class="card-body">
            <h1 class="card-title">85%</h1>
            <p class="card-text">リピート率</p>
          </div>
        </div>
      </div>

      <!--満足度-->
      <div class="col">
        <div class="card text-white bg-danger mb-3 shadow">
          <div class="card-body">
            <h1 class="card-title">99%</h1>
            <p class="card-text">満足度</p>
          </div>
        </div>
      </div>

      <!--挫折率-->
      <div class="col">
        <div class="card text-white bg-secondary mb-3 shadow">
          <div class="card-body">
            <h1 class="card-title">3%</h1>
            <p class="card-text">挫折率</p>
          </div>
        </div>
      </div>
    </div>
    <p class="text-muted">※独自のアンケート結果</p>
  </div>
</section>

app/views/landing_pages/index.html.erb
<!-- navigation bar -->
<%= render 'navbar' %>
<!-- contents -->
<!-- home -->
<%= render 'home' %>

<!-- course -->
<%= render 'course' %>

<!--reputation-->
<%= render 'reputation' %>

<!-- content -->
<%= render 'content' %>

<!-- pricing -->
<%= render 'pricing' %>

<!-- contact us -->
<%= render 'contactus' %>

<!-- footer -->
<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-100 vstack">
    <%= yield %>
  </body>
</html>

app/views/receipts/_navbar.html.erb
<nav id="navbar" class="navbar navbar-expand-md navbar-dark bg-dark bg-opacity-75 bg-gradient fixed-top">
  <div class="container">
    <%# <a class="navbar-brand" href="">Navbar</a> %>
    <%= link_to "Receipts", receipts_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <span class="navbar-text">
            user: <%= current_user.email %>
          </span>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else%>
          <li class="nav-item active">
            <a class="nav-link" type="button" data-bs-toggle="modal" data-bs-target="#signUpModal">Sign Up</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" type="button" data-bs-toggle="modal" data-bs-target="#logInModal">Sign In</a>
          </li>
        <% end%>
      </ul>
    </div>
  </div>
</nav>
<% unless user_signed_in? %>
  <%= render partial: 'devise/registrations/new' %>
  <%= render partial: 'devise/sessions/new' %>
<% end %>

app/views/receipts/_receipt_detail_fields.html.erb
<div class="nested-fields ">
<div class="row mb-3">
  <%= f.hidden_field :id %>
  <div class="col">
    <%= f.text_field :name, class: "form-control", placeholder: :name %>
  </div>
  <div class="col">
    <%= f.number_field :price, class: "form-control text-end", placeholder: :price %>
  </div>
  <div class="col">
    <%= f.number_field :quantity, class: "form-control text-end", placeholder: :quantity %>
  </div>
  <div class="col">
    <%= link_to_remove_association "<i class='bi bi-x'></i> 削除".html_safe, f, class: 'btn btn-sm btn-danger' %>
  </div>
</div>
</div>

app/views/receipts/edit.html.erb
<h1>Receipts#edit</h1>
<p>Find me in app/views/receipts/edit.html.erb</p>

<div class="container">
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@receipt.errors.count, "error") %>.
      </div>
      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form_with(model: @receipt, local: true) do |f| %>
      <div class="col-sm-3 mb-3">
        <%= f.label :total_price, class: "form-label" %>
        <%= f.number_field :total_price, class: "form-control text-end", readonly: true %>
      </div>
      <%= f.label :receipt_details, class: "form-label" %>
      <div class="mb-3" id="details">
        <%= f.fields_for :receipt_details do |df| %>
          <%= render "receipt_detail_fields", f: df %>
        <% end %>
      </div>
      <div>
        <%= link_to_add_association "<i class='bi bi-plus'></i> 追加".html_safe, f, :receipt_details, class: "btn btn-sm btn-secondary",
          data: { association_insertion_node: '#details', association_insertion_method: 'append' } %>
      </div>

      <div class="text-center">
        <%= f.submit "更新", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    sum();
    addEvent($("#details"));
    
    $("#details")
    .on("cocoon:after-insert", function(e, insertedItem) {
      addEvent(insertedItem);
    })
    .on("cocoon:after-remove", function() {
      sum();
    });

    function addEvent(obj) {
      $(obj).find("input").change(function(){
        sum();
      });
    };
    function sum() {
      let total = 0;
      $("#details .row").each(function(index, row){
        const price = $(row).find("input[id$='price']").val();
        const quantity = $(row).find("input[id$='quantity']").val();
        const isDestroy = $(row).find("input[id$='_destroy']").val() != "false";
        if (price && quantity && !isDestroy) {
          total += price * quantity;
        }
      });
      $("#receipt_total_price").val(total);
    }
  });
</script>

app/views/receipts/index.html.erb
<%= render 'navbar' %>
<h1>Receipts#index</h1>
<p>Find me in app/views/receipts/index.html.erb</p>

<div class="container">
  <table class="table">
    <thead>
      <tr class="text-center">
        <th>#</th>
        <th>Date</th>
        <th>Items</th>
        <th>Total Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @receipts.each do |receipt| %>
      <tr>
        <td class="text-center"><%= receipt.id %></td>
        <td class="text-center"><%= receipt.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M:%S') %></td>
        <td class="text-end"><%= receipt.receipt_details.count %></td>
        <td class="text-end"><%= receipt.total_price.to_s(:delimited) %></td>
        <td class="text-center">
          <%= link_to edit_receipt_path(receipt.id), class:"btn btn-sm btn-warning" do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
          <%= link_to receipt_path(receipt.id), method: :delete, class:"btn btn-sm btn-danger", data: { confirm: 'Are you sure?' } do %>
            <i class="bi bi-x-square"></i>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="col">
      <%= will_paginate @receipts, previous_label: '&lt; Prev', next_label: 'Next &gt;' %>
    </div>
    <div class="col-sm-2">
      <%= link_to new_receipt_path, class: "btn btn-success" do %>
        <i class="bi bi-receipt-cutoff"></i> add receipt
      <% end %>
    </div>
  </div>
</div>

app/views/receipts/new.html.erb
<h1>Receipts#new</h1>
<p>Find me in app/views/receipts/new.html.erb</p>

<div class="container">
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@receipt.errors.count, "error") %>.
      </div>
      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form_with(model: @receipt, local: true) do |f| %>
      <div class="col-sm-3 mb-3">
        <%= f.label :total_price, class: "form-label" %>
        <%= f.number_field :total_price, class: "form-control text-end", readonly: true %>
      </div>
      <%= f.label :receipt_details, class: "form-label" %>
      <div class="mb-3" id="details">
        <%= f.fields_for :receipt_details do |df| %>
          <%= render "receipt_detail_fields", f: df %>
        <% end %>
      </div>
      <div>
        <%= link_to_add_association "<i class='bi bi-plus'></i> 追加".html_safe, f, :receipt_details, class: "btn btn-sm btn-secondary",
          data: { association_insertion_node: '#details', association_insertion_method: 'append' } %>
      </div>

      <div class="text-center">
        <%= f.submit "登録", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    sum();
    addEvent($("#details"));
    
    $("#details")
    .on("cocoon:after-insert", function(e, insertedItem) {
      addEvent(insertedItem);
    })
    .on("cocoon:after-remove", function() {
      sum();
    });

    function addEvent(obj) {
      $(obj).find("input").change(function(){
        sum();
      });
    };
    function sum() {
      let total = 0;
      $("#details .row").each(function(index, row){
        const price = $(row).find("input[id$='price']").val();
        const quantity = $(row).find("input[id$='quantity']").val();
        if (price && quantity) {
          total += price * quantity;
        }
      });
      $("#receipt_total_price").val(total);
    }
  });
</script>